//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDR_MAINFRAME                   114
#define IDR_TRACKMAP                    120
#define IDR_FILEMANAGER                 122
#define IDR_MDOS                        127
#define IDR_MDOS_FILE_ATTRIBUTES_EDITOR 132
#define IDR_MDOS_DRIVE_EDITOR           136
#define IDR_IMAGE_NEW                   138
#define IDR_DOS_FORMAT                  140
#define IDR_DOS_UNFORMAT                143
#define IDR_DOS_FILL_EMPTY_SPACE        145
#define IDR_DOS_UNKNOWN                 146
#define IDR_MDOS_GKFM_EDITOR            152
#define IDR_ZX_TAPE                     156
#define IDR_FILEMANAGER_COMPARE_FILES   158
#define IDR_TRDOS                       159
#define IDR_HEXAEDITOR                  160
#define IDR_OPEN_CUSTOM                 161
#define IDR_MSDOS                       162
#define IDR_ACTION_PROGRESS             163
#define IDR_GDOS                        164
#define IDR_IMAGE_DUMP                  165
#define IDR_MSDOS_FILE_ATTRIBUTES_EDITOR 166
#define IDR_FILEMANAGER_SUBDIR_NEW      167
#define IDR_FILEMANAGER_IMPORT_CONFLICT 168
#define IDR_MSDOS_REMOVE_LONG_NAMES     169
#define IDR_ACTION_DIALOG               170
#define IDR_DSK_TYPE                    171
#define IDR_IMAGE_DUMP_ERROR            172
#define IDR_FDD_ACCESS                  173
#define IDR_IMAGE                       174
#define IDR_FDD_LATENCY                 181
#define IDR_WEBPAGE                     183
#define IDR_IMAGE_DUMP_ERROR_RESOLUTION 185
#define IDR_IMAGE_PATCH                 186
#define IDR_DOS_PROPGRID_HEXAEDITOR     188
#define IDR_DOS_RECOGNITION             189
#define IDR_SPECTRUM_PREVIEW_BASIC      193
#define IDR_RAW_SETTINGS                196
#define IDR_MISC                        201
#define IDR_SCATTERPLOT                 202
#define IDR_SINGLE_NUMBER               204
#define IDR_DISKBROWSER                 205
#define IDR_DISKBROWSER_GOTOSECTOR      206
#define IDR_DIRECTORYBROWSER            207
#define IDR_DOS_DATETIME_EDIT           208
#define IDR_HEXAEDITOR_RESETSELECTION   209
#define IDR_SPECTRUM_PREVIEW_SCREEN     210
#define IDR_GUIDEPOST                   211
#define IDR_TRACKMAP_CONTEXT            212
#define IDR_BSDOS                       213
#define IDR_DOS_VERIFY                  214
#define IDR_FILEMANAGER_FOCUSED_CONTEXT 215
#define IDR_ACTION_SEQUENCE             216
#define IDR_DRIVE_ACCESS                217
#define IDR_SPECTRUM_PREVIEW_ASSEMBLER  218
#define IDR_DOS_PREVIEW_BASE            219
#define IDR_CAPS_DEVICE_ACCESS          220
#define IDR_CAPS                        221
#define IDR_TRACK_EDITOR                222
#define IDR_CHARTFRAME_XY               223
#define IDR_CAPS_PRECOMPENSATION        224
#define IDR_CAPS_CORRECTIONS            225
#define IDR_TRACK_EDITOR_GOTO_TIME      226
#define IDR_FILEMANAGER_GENERAL_CONTEXT 227
#define IDR_FDD_TEST                    228
#define IDR_TRACK_EXPORT                230
#define ID_HIDDEN                       1018
#define ID_SYSTEM                       1019
#define ID_CONNECTED                    1020
#define ID_PROTECTED                    1021
#define ID_ERROR                        1022
#define ID_ARCHIVE                      1023
#define ID_DRIVEA                       1024
#define ID_READABLE                     1025
#define ID_DRIVEB                       1026
#define ID_WRITABLE                     1027
#define ID_D80                          1028
#define ID_EXECUTABLE                   1029
#define ID_D40                          1030
#define ID_DELETABLE                    1031
#define ID_DSFLOPPY                     1032
#define ID_40D80                        1033
#define ID_TRACK                        1034
#define ID_STEPPING                     1035
#define ID_ZERO                         1036
#define ID_CYLINDER                     1037
#define ID_DOS                          1038
#define ID_NONE                         1039
#define ID_HEAD                         1043
#define ID_SIZE                         1044
#define ID_FORMAT                       1045
#define ID_CYLINDER_N                   1046
#define ID_CODEC                        1047
#define ID_GAP                          1048
#define ID_MEDIUM                       1049
#define ID_CLUSTER                      1050
#define ID_INTERLEAVE                   1051
#define ID_SKEW                         1052
#define ID_X                            1057
#define ID_COLOR                        1058
#define ID_BRIGHT                       1059
#define ID_DX                           1060
#define ID_ALIGN                        1062
#define ID_FILE_SHIFT_UP                1066
#define ID_FILE_SHIFT_DOWN              1067
#define ID_STATE                        1079
#define ID_READONLY                     1094
#define ID_VOLUME                       1095
#define ID_ATTRIBUTE                    1098
#define ID_APPLY                        1099
#define ID_DEFAULT1                     1100
#define ID_DEFAULT2                     1101
#define ID_DEFAULT3                     1102
#define ID_DEFAULT4                     1103
#define ID_DEFAULT5                     1104
#define ID_DEFAULT6                     1105
#define ID_DEFAULT7                     1106
#define ID_DEFAULT8                     1107
#define ID_REPORT                       1108
#define ID_DRIVE                        1109
#define ID_INFORMATION                  1110
#define ID_STANDARD                     1113
#define ID_LATENCY                      1116
#define ID_AUTO                         1117
#define ID_RECOVER                      1119
#define ID_DATAFIELD_FILLERBYTE         1123
#define ID_DATAFIELD_REPLACE            1124
#define ID_FLOPPY_DD                    1125
#define ID_FLOPPY_HD                    1126
#define ID_TEST                         1127
#define ID_ACCURACY                     1128
#define ID_DATAFIELD_CRC                1129
#define ID_VERIFY_TRACK                 1131
#define ID_VERIFY_SECTOR                1132
#define ID_SEEK                         1133
#define ID_ROTATION                     1134
#define ID_ADD                          1140
#define ID_REMOVE                       1141
#define ID_ORDER                        1142
#define ID_UP                           1143
#define ID_DOWN                         1144
#define ID_IDFIELD                      1145
#define ID_IDFIELD_CRC                  1146
#define ID_IDFIELD_REPLACE              1147
#define ID_IDFIELD_VALUE                1148
#define ID_DATAFIELD                    1149
#define ID_CREATOR                      1151
#define ID_PRIORITY                     1155
#define ID_BUFFER                       1156
#define ID_HELP_DONATE                  1157
#define ID_SIDE                         1165
#define ID_DATE                         1171
#define ID_TIME                         1173
#define ID_BOOT                         1175
#define ID_FAT                          1176
#define ID_FILE1                        1177
#define ID_FILE2                        1178
#define ID_IMAGE                        1179
#define ID_TEXT                         1182
#define ID_REPAIR                       1183
#define ID_TDI_SWITCH                   40033
#define ID_TDI_SWITCH_BACK              40034
#define ID_EDIT_SELECT_NONE             40057
#define ID_EDIT_SELECT_INVERSE          40058
#define ID_EDIT_SELECT_TOGGLE           40059
#define ID_BOOKMARK_TOGGLE              40062
#define ID_DATA                         40068
#define ID_RECURRENCY                   40080
#define ID_FILE                         40081
#define ID_SECTOR                       40082
#define ID_DIRECTORY                    40084
#define ID_DELETE                       40085
#define ID_SUBDIRECTORY                 40086
#define ID_TRACKMAP_LEGEND              40087
#define ID_CREDITS                      40091
#define ID_DOS_UNFORMAT                 40095
#define ID_NUMBER                       40096
#define ID_DOS_FORMAT                   40097
#define ID_NUMBER2                      40098
#define ID_OPEN_AS                      40101
#define ID_OPEN_UNKNOWN                 40103
#define ID_TAPE_NEW                     40108
#define ID_TAPE_APPEND                  40109
#define ID_TAPE_OPEN                    40110
#define ID_ZX_PREVIEWASSCREEN           40112
#define ID_MDOS_AUTODETECT              40134
#define ID_MDOS_VERSION1                40135
#define ID_MDOS_VERSION2                40136
#define ID_REVOLUTION_PREV              40137
#define ID_REVOLUTION_NEXT              40138
#define ID_HELP_FAQ                     40139
#define ID_TAPE_CLOSE                   40147
#define ID_IMAGE_DUMP                   40148
#define ID_IMAGE_PATCH                  40149
#define ID_IMAGE_PROTECT                40150
#define ID_IMAGE_BROWSE                 40151
#define ID_IMAGE_SETTINGS               40152
#define ID_DOS_FILE_LENGTH_FROM_DIRENTRY 40156
#define ID_DOS_FILE_LENGTH_OCCUPIED_SECTORS 40157
#define ID_TRACKMAP_STATUS              40158
#define ID_TRACKMAP_DATA                40159
#define ID_TRACKMAP_BAD_DATA            40160
#define ID_TRACKMAP_STATISTICS          40161
#define ID_DOS_VERIFY                   40163
#define ID_DOS_DEFRAGMENT               40164
#define ID_DOS_FILL_EMPTY_SPACE         40165
#define ID_MSDOS_REMOVE_LONG_NAMES      40166
#define ID_MSDOS_IGNORE_LONG_NAMES      40167
#define ID_FILEMANAGER_FILE_EDIT        40169
#define ID_FILEMANAGER_FILE_DELETE      40170
#define ID_FILEMANAGER_BIG_ICONS        40171
#define ID_FILEMANAGER_REPORT           40172
#define ID_FILEMANAGER_SMALL_ICONS      40173
#define ID_FILEMANAGER_LIST             40174
#define ID_FILEMANAGER_FILE_COMPARE     40175
#define ID_FILEMANAGER_REFRESH          40176
#define ID_TRACKMAP_NUMBERING           40178
#define ID_APP_UPDATE                   40185
#define ID_WEB_NAVIGATE_BACK            40187
#define ID_WEB_NAVIGATE_FORTH           40188
#define ID_WEB_DEFAULT_BROWSER          40189
#define ID_DOS_PREVIEWASBINARY          40191
#define ID_FILEMANAGER_SUBDIR_CREATE    40192
#define ID_FILEMANAGER_FILE_INFORMATION 40193
#define ID_MSDOS_IGNOREDOT              40194
#define ID_MSDOS_IGNOREDOTDOT           40195
#define ID_MDOS_IMPORTATTRIBUTES_CUSTOM 40205
#define ID_DOS_FILE_ZERO_LENGTH         40206
#define ID_RECOGNIZE                    40207
#define ID_DOS_SHELLCOMPLIANTNAMES      40208
#define ID_DOS_TAKEATOUR                40210
#define ID_ZX_PREVIEWASBASIC            40211
#define ID_PRINT                        40213
#define ID_NEXT                         40214
#define ID_PREV                         40215
#define ID_ZX_BASIC_BINARY_DONTSHOW     40217
#define ID_ZX_BASIC_BINARY_SHOWRAW      40218
#define ID_ZX_BASIC_BINARY_SHOWNUMBER   40219
#define ID_HELP_REPORT_BUG              40221
#define ID_FILEMANAGER_DIR_HEXAMODE     40223
#define ID_EDIT_DELETE                  40227
#define ID_BOOKMARK_NEXT                40230
#define ID_HELP_REPOSITORY              40232
#define ID_HELP_TUTORIALS               40233
#define ID_EDIT_SELECT_CURRENT          40239
#define ID_BOOKMARK_PREV                40240
#define ID_NAVIGATE_ADDRESS             40241
#define ID_SELECT_CURRENT_TRACK         40246
#define ID_SELECT_CURRENT_CYLINDER      40247
#define ID_NAVIGATE_PREVIOUSCYLINDER    40248
#define ID_NAVIGATE_NEXTCYLINDER        40251
#define ID_NAVIGATE_NEXTTRACK           40252
#define ID_NAVIGATE_PREVIOUSTRACK       40253
#define ID_NAVIGATE_SECTOR              40254
#define ID_NAVIGATE_UP                  40255
#define ID_BOOKMARK_DELETEALL           40257
#define ID_COMPUTE_CHECKSUM             40260
#define ID_ZOOM_FIT                     40266
#define ID_ZOOM_OUT                     40267
#define ID_ZOOM_IN                      40268
#define ID_ZOOM_PART                    40269
#define ID_ADDRESS                      40271
#define ID_YAHEL_REPOSITORY             40272
#define ID_YAHEL_ABOUT                  40273
#define ID_ZX_PREVIEWASASSEMBLER        40277
#define ID_PREV_BAD                     40278
#define ID_NEXT_BAD                     40279
#define ID_VARIABLE                     40280
#define ID_INSTRUCTION                  40281
#define ID_COMMENT                      40283
#define ID_TRACKMAP_TIMING              40285
#define ID_OPEN_DEVICE                  40286
#define ID_CHART                        40288
#define ID_HISTOGRAM                    40289
#define ID_REFRESH                      40290
#define ID_Y                            58113
#define ID_W                            58114
#define ID_H                            58115
#define ID_INK                          58116
#define ID_PAPER                        58117
#define ID_DY                           58118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         40291
#define _APS_NEXT_CONTROL_VALUE         1185
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
